name = "YNABJL"
uuid = "41e38347-8d7c-4559-93e1-9c7fb7be9f6b"
authors = ["Jonathan Oxborrow <jonathan.todd.oxborrow@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
